from pathlib import Path
from scripts.get_vars import *
import sys
import pandas as pd


def _resolve(p):
    """Resolve a config path to absolute, relative to the workflow directory."""
    p = Path(p)
    return p if p.is_absolute() else (Path(workflow.basedir) / p).resolve()


DATADIR  = _resolve(config.get('dataDir',  config.get('data_dir',  'data')))
OUTDIR   = _resolve(config.get('outDir',   config.get('output_dir', 'output')))
ADAPTERS = _resolve(config.get('adapters', ''))
PHIX     = _resolve(config.get('phix',     ''))

samples_file = config.get('samples', '')
if samples_file:
    samples_file = str(_resolve(samples_file))
    sampleInfo = pd.read_csv(samples_file)
    samples_to_merge = (sampleInfo.loc[sampleInfo.groupby('sample')
                        .unit.filter(lambda x: x.nunique() > 1).index]['sample']
                        .unique())
    SAMPLES = pd.read_csv(samples_file, comment='#')['sample'].unique()
else:
    SAMPLES = config.get('sample', [])
    sampleInfo = None

if len(SAMPLES) == 0:
    ValueError("Provide samples via 'samples'")

include: "rules/preprocess.smk"
include: "rules/assemble.smk"
# include: "rules/quast.smk"
# include: "rules/alignment.smk"
include: "rules/annotate.smk"
# include: "rules/compare_genomes.smk"
include: "rules/call_variants.smk"
include: "rules/instrain.smk"
include: "rules/ismap.smk"
# include: "rules/typing.smk"
# include: "rules/profile.smk"

# geNomad phage/provirus detection is a standalone workflow (Snakefile_phage,
# rules/phage.smk) run via `nccrPipe phage`; it is intentionally not wired into
# the samples.csv-driven main pipeline.


"""
PREPROCESSING
In the config file, can specify whether to run FastQC before preprocessing, after, both or not at all.
By default, will only run after preprocessing.
"""

fastqc_config = config.get('fastqc', '')

if not fastqc_config:
    rule preprocess:
        input:
            [
                f'{OUTDIR}/clean_reads/{sample}/{sample}.qc.done' for sample in SAMPLES]

elif fastqc_config == 'after':
    rule preprocess:
        input:
            clean_files = [
                f'{OUTDIR}/clean_reads/{sample}/{sample}.qc.done' for sample in SAMPLES],
            fastqc = [
                f'{OUTDIR}/fastqc_clean/{sample}.fastqc_clean.done' for sample in SAMPLES]

elif fastqc_config == 'before':
    rule preprocess:
        input: f'{OUTDIR}/fastqc/before.multiqc.done'
elif fastqc_config == 'both':
    rule preprocess:
        input: f'{OUTDIR}/fastqc/both.multiqc.done'
else:
    print(f'{fastqc_config} is not a recognized option for fastqc')
    sys.exit(1)

rule merge_fastq:
    input:
        [OUTDIR /
            f'merged_reads/{sample}/{sample}.merge.done' for sample in SAMPLES]

"""
ASSEMBLY and ANNOTATION

In the config specify whether to use spades or unicycler. Default will be spades

"""

assembler_config = config.get('assembler', 'spades')
assembler_mode_config = config.get('unimode', '')
if assembler_config == 'spades':
    GFFs = [
        f'{OUTDIR}/assembly/{sample}/{sample}.scaffolds.min200.prokka.done' for sample in SAMPLES]
elif assembler_config == 'unicycler':
    GFFs = [
        f'{OUTDIR}/unicycler/{assembler_mode_config}/{sample}/assembly.prokka.done' for sample in SAMPLES]
else:
    GFFs = []

rule assemble:
    input: GFFs


gapseq_files = [f'{OUTDIR}/gapseq_output/{f.stem}/{f.stem}-Transporter.tbl' for f in (
    OUTDIR/"gapseq_data").glob("*.faa") if 'all-strains' not in f.stem]
print(gapseq_files)
rule run_gapseq:
    # input: OUTDIR/"gapseq_output/Rahnella_38_1_0.25/Rahnella_38_1_0.25-all-Pathways.tbl"
    input: gapseq_files


"""

Variant Calling

"""

VCFs = []
BAMs = []
reference_config = config.get('reference', {})

for ref, samples in reference_config.items():
    if ref == 'refDir' or ref == 'refgbk':
        continue
    BAMs += [f'{OUTDIR}/bams/{sample}/{sample}_to_{ref}.bam' for sample in samples]
    VCFs += [f'{OUTDIR}/VCF/{sample}/{sample}_to_{ref}.isolate.filtered.vcf' for sample in samples]


rule align:
    input: BAMs

rule varcall:
    input: VCFs

breseq_done = [f'{OUTDIR}/breseq/{sample}.breseq.done' for sample in SAMPLES]
rule breseq:
    input: breseq_done

"""
InStrain — strain-level microdiversity profiling and cross-sample comparison.
Reuses the BAMs from `align` (reads mapped to each reference in reference_config).
"""
IS_PROFILES = []
IS_COMPARES = []
_run_compare = config.get('instrain', {}).get('run_compare', True)
for ref, samples in reference_config.items():
    if ref in ('refDir', 'refgbk', 'refgff'):
        continue
    IS_PROFILES += [f'{OUTDIR}/instrain/profiles/{sample}_to_{ref}/.IS.profile.done' for sample in samples]
    if _run_compare and len(samples) >= 2:
        IS_COMPARES += [f'{OUTDIR}/instrain/compare/{ref}/.IS.compare.done']

rule instrain:
    input: IS_PROFILES

rule instrain_compare:
    input: IS_COMPARES

"""
ISMapper — insertion sequence (IS) site detection against reference.refgbk.
"""
rule ismap:
    input: [f'{OUTDIR}/ismap/{sample}/.ismap.done' for sample in SAMPLES]

"""
Annotation

"""
db = config.get('database', '')
if assembler_config == 'spades':
    FAAs = [
        f'{OUTDIR}/assembly/{sample}/{db}/{sample}.{db}.done' for sample in SAMPLES]
elif assembler_config == 'unicycler':
    FAAs = [
        f'{OUTDIR}/unicycler/{assembler_mode_config}/{sample}/{db}/{sample}.{db}.done' for sample in SAMPLES]
else:
    FAAs = []

rule annotate:
    input: FAAs


# if config['assembler'] == 'spades':
#
#     rule assemble_only:
#         input: [OUTDIR/f'assembly/{sample}/{sample}.assembly_cleanup.done' for sample in SAMPLES]
#
#     rule assemble:
#         input: [OUTDIR/f'assembly/{sample}/prokka/{sample}.prokka.done' for sample in SAMPLES],
#        # [OUTDIR/f'assembly/{sample}/eggnog/{sample}.eggnog.done' for sample in SAMPLES]
#
#
# elif config['assembler'] == 'unicycler':
#
#     rule assemble:
#         input:[OUTDIR/f'unicycler/{config["unimode"]}/{sample}/{sample}.unicycler.done' for sample in SAMPLES]
#
#     # rule quastCheck:
#     #     input: OUTDIR/f'unicycler/{config["unimode"]}/unicycler_assembly_qc.quast_all.done'
#
# else:
#     print(f'{config["assembler"]} is not a recognized option for assembler. Options: [spades, unicycler]')
#     sys.exit(1)
#
# rule annotate:
#     pass

# rule quastCheck:
#     input: OUTDIR/'quast/assembly_qc.quast_all.done'
#
#
# rule compare_genelen:
#     input: "/science/ansintsova/bioinfocore/aligner_test/data/assembly/Sal/Sal.scaffolds.min500.fasta.genelen.done"
#
# rule compare_genelen_uni:
#     input: "/science/ansintsova/bioinfocore/aligner_test/data/unicycler/normal/Sal/assembly.fasta.genelen.done"
#
# """
#
# VARIANT CALLING
#
# """
#
# rule align:
#     input: [OUTDIR/f'bams/{sub}/{sub}.bwa.done' for sub in SAMPLES]
#
# rule align_with_ref:
#     input: [OUTDIR/f'ref_bams/{sub}/{sub}.refbwa.done' for sub in SAMPLES]
#
# rule alignment_qc:
#     input: [OUTDIR/f'ref_bams/{sample}/{sample}.bam.stats' for sample in SAMPLES]
#
# rule pileup:
#     input: [OUTDIR/f'VCF/{sub}/{sub}.mpileup' for sub in SAMPLES]
#
# rule anVar:
#     input: [OUTDIR/f'VCF/{sub}/{sub}.snpEff.done' for sub in SAMPLES]
#
# rule addGenomeSnpEff:
#     input: OUTDIR/f'VCF/{config["snpEff_reference"]}.snpEff_db.done'
#
# rule call_variants:
#     input: [OUTDIR/f'VCF/{sub}/{sub}.isolate.vcf.done' for sub in SAMPLES]
#
# rule call_vars3:
#     input: [OUTDIR/f'VCF/{sub}/{sub}.f3.vcf.done' for sub in SAMPLES]
#
# rule markDup:
#     input: [OUTDIR/f'bams/{sub}/{sub}.rmdup.bam' for sub in SAMPLES]
#
#
# """
# OTHER
#
# """
#
# rule count_htseq:
#     input: [OUTDIR/f'counts/{sample}/{sample}.tsv' for sample in SAMPLES]
# # Compare Genomes
#
# rule nucmer:
#     input: [OUTDIR/f'mummer/LL23_{sample}.coords' for sample in SAMPLES]
#
# rule runANI:
#     input: [OUTDIR/f'ANI/assembly/{i}_{j}_fastani.out' for i in SAMPLES for j in SAMPLES]
#
# rule motus:
#     input: [OUTDIR/f'motus/{sample}/{sample}.motus' for sample in SAMPLES]
#
# rule fetchMG:
#     input: [OUTDIR/f'fetchMG/{sample}/fetchMG.done' for sample in SAMPLES]
#
# rule whatisit:
#     input: [OUTDIR/f'mash/{sample}/{sample}.distances.tab' for sample in SAMPLES]
#
# rule anVar2:
#     input: [OUTDIR/f'VCF/{sub}/{sub}.AF.snpEff.done' for sub in SAMPLES]

# rule gzip:
#     input: '{sample}.fasta',
#     output: '{sample}.fasta.gz',
#     params:
#         qerrfile = '{sample}.gzip.qerr',
#         qoutfile = '{sample}.gzip.qout',
#         scratch = 6000,
#         mem = 7700,
#         time = 1400
#     threads:
#         8
#     shell:
#         'gzip {input}'


# 2021-02-24 Trees for algal metagenomes

# rule algal_tree:
#     #input: '/nfs/nas22/fs2202/biol_micro_bioinf_nccr/piel/padhi/data/fresh_tree/fresh.bac120.user_msa.fasta.iqtree'
#     #input: '/nfs/nas22/fs2202/biol_micro_bioinf_nccr/piel/padhi/data/trees/fresh_tree/fresh.bac120.user_msa.fasta.iqtree'
#     input: '/nfs/nas22/fs2202/biol_micro_bioinf_nccr/piel/padhi/data/trees/sed_tree/sed.bac120.user_msa.fasta.iqtree', '/nfs/nas22/fs2202/biol_micro_bioinf_nccr/piel/padhi/data/trees/2017_2020_tree/2017_2020.bac120.user_msa.fasta.iqtree'
#
