projectName: Test_Isolate_Assembly

# Use same raw data for assembly as for variant calling
# LL23 reads that alligned to LL6_1 contig

dataDir: test_data/varcall_test_data/raw
outDir: test_data/assembly_test_data/output
sampleFile: test_data/varcall_test_data/test_samples.txt
fq_fwd: _R1.fq.gz
fq_rvr: _R2.fq.gz


#Preprocessing
qc: yes
mink: 11
trimq: 14
mapq: 20
minlen: 45

merged: false # By default do not use merge for isolate genome assembly
fastqc: no # Options: no, before, after, both

# Assembler:
assembler: spades # Options: spades and unicycler

# Unicycler options:
unimode: normal

# Look at gene lengths distribution
diamondDB: /science/ansintsova/bioinfocore/aligner_test/data/finished_assemblies/Sal_db


# Standard parameters. Dont change these!!!
adapters: ../../../data/adapters/adapters.fa
phix: ../../../data/adapters/phix174_ill.ref.fa.gz
bbmap_human_ref: '/nfs/cds-shini.ethz.ch/exports/biol_micro_cds_gr_sunagawa/SequenceStorage/resources/human_bbmap_ref/'
bbmap_mouse_ref: '/nfs/cds-shini.ethz.ch/exports/biol_micro_cds_gr_sunagawa/SequenceStorage/resources/mouse_bbmap_ref/'

