projectName: Test_Variant_Calling

dataDir: test_data/varcall_test_data/raw
outDir: test_data/varcall_test_data/output
sampleFile: test_data/varcall_test_data/test_samples.txt
fq_fwd: _R1.fq.gz
fq_rvr: _R2.fq.gz


#Preprocessing
qc: yes
mink: 11
trimq: 14
mapq: 20
minlen: 45

merged: false # By default do not use merge for isolate genome assembly
fastqc: no # Options: no, before, after, both


# Align to reference
# Had to compress with bgzip for bcftools to work
reference: test_data/varcall_test_data/LL6_1.fasta.gz

# Variant Annotation
snpEff_root: /nfs/home/ansintsova/./miniconda3/pkgs/snpeff-5.0-0/share/snpeff-5.0-0/
snpEff_reference: LL6

# Standard parameters. Dont change these!!!
adapters: ../../../data/adapters/adapters.fa
phix: ../../../data/adapters/phix174_ill.ref.fa.gz
bbmap_human_ref: '/nfs/cds-shini.ethz.ch/exports/biol_micro_cds_gr_sunagawa/SequenceStorage/resources/human_bbmap_ref/'
bbmap_mouse_ref: '/nfs/cds-shini.ethz.ch/exports/biol_micro_cds_gr_sunagawa/SequenceStorage/resources/mouse_bbmap_ref/'

